before_script:
  - export MODULEPATH=/scratch/spack-22.1/share/spack/modules/linux-ubuntu18.04-skylake_avx512:/scratch/spack-22.1/share/spack/modules/linux-ubuntu18.04-x86_64
  - module load PrgEnv/gcc11-openmpi-python
  - module load itensor/itensor-3.1.10/itensor-3.1.10-gcc-11.2.0-openmpi-mkl-t6r65sm
  - export CCACHE_DIR="/var/tmp/$USER/ccache_PITTS/"
  - export OMP_NUM_THREADS=5
  - ulimit -s unlimited
  - export OMP_STACKSIZE=20M
  - export CXX="ccache g++"
  - ccache -z

after_script:
  - CCACHE_DIR="/var/tmp/$USER/ccache_PITTS/" ccache -s

build_release:
  stage: build
  variables:
    SCHEDULER_PARAMETERS: "-p cpu -N 1 -n 7 -c 4 -t 00:10:00"
  needs: []
  script:
    - mkdir build_release && cd build_release
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . -- -j 8
    - cmake --build . --target check -j 8
  artifacts:
    reports:
      junit: build_release/test/pitts_tests*.xml

build_coverage:
  stage: build
  variables:
    SCHEDULER_PARAMETERS: "-p cpu -N 1 -n 7 -c 4 -t 00:10:00"
  needs: []
  script:
    - mkdir build_coverage && cd build_coverage
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=On
    - cmake --build . -- -j 8
    - cmake --build . --target check -j 8
  coverage: '/^\s*lines:\s*\d+.\d+\% \(\d+ out of \d+\)$/'
  artifacts:
    reports:
      junit: build_coverage/test/pitts_tests*.xml
      cobertura: build_coverage/test/coverage.xml
    paths:
      - build_coverage/test/coverage*.html

pages:
  stage: deploy
  dependencies:
    - build_coverage
  script:
    - mkdir -p public/coverage
    - mv build_coverage/test/coverage.*.html public/coverage/
    - mv build_coverage/test/coverage.html public/coverage/index.html
  artifacts:
    paths:
      - public/
    expire_in: 30 days
  only:
    - master
