before_script:
  - export MODULEPATH=/scratch/spack-22.2/share/spack/modules/linux-ubuntu20.04-skylake_avx512
  - module load PrgEnv/gcc11-openmpi-python
  - export CCACHE_DIR="/var/tmp/gitlab-runner/ccache_PITTS/"
  - export OMP_NUM_THREADS=5
  - ulimit -s unlimited
  - export OMP_STACKSIZE=20M
  - export CXX=g++

build_release:
  stage: build
  variables:
    SCHEDULER_PARAMETERS: "-p cpu -N 1 -n 7 -c 4 -t 00:10:00"
  needs: []
  script:
    - ccache -z
    - mkdir build_release && cd build_release
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - cmake --build . -- -j 28
    - cmake --build . --target check -j 28
    - ccache -s
  artifacts:
    reports:
      junit: build_release/test/pitts_tests*.xml

build_debug_with_coverage:
  stage: build
  variables:
    SCHEDULER_PARAMETERS: "-p cpu -N 1 -n 7 -c 4 -t 00:15:00"
  needs: []
  script:
    - ccache -z
    - mkdir build_coverage && cd build_coverage
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=On -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - cmake --build . -- -j 28
    - cmake --build . --target check -j 28
    - ccache -s
  coverage: '/^\s*lines:\s*\d+.\d+\% \(\d+ out of \d+\)$/'
  artifacts:
    reports:
      junit: build_coverage/test/pitts_tests*.xml
      coverage_report:
        coverage_format: cobertura
        path: build_coverage/test/coverage.xml
    paths:
      - build_coverage/test/coverage*.html

build_debug_no_itensor:
  stage: build
  variables:
    SCHEDULER_PARAMETERS: "-p cpu -N 1 -n 7 -c 4 -t 00:10:00"
  needs: []
  script:
    - ccache -z
    - module unload -f itensor
    - mkdir build_debug && cd build_debug
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - cmake --build . -- -j 28
    - cmake --build . --target check -j 28
    - ccache -s
  artifacts:
    reports:
      junit: build_debug/test/pitts_tests*.xml

pages:
  stage: deploy
  dependencies:
    - build_debug_with_coverage
  script:
    - mkdir -p public/coverage
    - mv build_coverage/test/coverage.*.html public/coverage/
    - mv build_coverage/test/coverage.html public/coverage/index.html
  artifacts:
    paths:
      - public/
    expire_in: 30 days
  only:
    - master
