before_script:
  - export OMP_NUM_THREADS=5
  - ulimit -s unlimited
  - ulimit -l unlimited
  - export OMP_STACKSIZE=20M
  - export SLURM_OVERLAP=1

build_release:
  stage: build
  variables:
    SCHEDULER_PARAMETERS: "-p cpu -N 1 -n 3 -c 5 -t 00:10:00"
  needs: []
  script:
    - export MODULEPATH=/scratch/spack-23.2/share/spack/modules/linux-ubuntu20.04-x86_64_v3
    - module load PrgEnv/gcc13-openmpi-python
    - export CCACHE_DIR="/var/tmp/gitlab-runner/ccache_PITTS/"
    - ccache -z
    - mkdir build_release && cd build_release
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=g++
    - cmake --build . -- -j 15
    - cmake --build . --target check -j 15
    - ccache -s
  artifacts:
    reports:
      junit: build_release/test/pitts_tests*.xml

build_debug_with_coverage:
  stage: build
  variables:
    SCHEDULER_PARAMETERS: "-p cpu -N 1 -n 3 -c 5 -t 00:15:00"
  needs: []
  script:
    - export MODULEPATH=/scratch/spack-23.2/share/spack/modules/linux-ubuntu20.04-x86_64_v3
    - module load PrgEnv/gcc13-openmpi-python
    - module unload -f itensor
    - export CCACHE_DIR="/var/tmp/gitlab-runner/ccache_PITTS/"
    - ccache -z
    - mkdir build_coverage && cd build_coverage
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=On -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=g++ -DPITTS_DEVELOP_BUILD=Off -DPITTS_EIGEN_USE_LAPACKE=On -DPITTS_OPTIMIZE_FOR_HOST=False
    - cmake --build . -- -j 15
    - cmake --build . --target check -j 15
    - ccache -s
  coverage: '/^\s*lines:\s*\d+.\d+\% \(\d+ out of \d+\)$/'
  artifacts:
    reports:
      junit: build_coverage/test/pitts_tests*.xml
      coverage_report:
        coverage_format: cobertura
        path: build_coverage/test/coverage.xml
    paths:
      - build_coverage/test/coverage*.html

build_debug_no_itensor:
  stage: build
  variables:
    SCHEDULER_PARAMETERS: "-p cpu -N 1 -n 3 -c 5 -t 00:15:00"
  needs: []
  script:
    - export MODULEPATH=/scratch/spack-23.2/share/spack/modules/linux-ubuntu20.04-x86_64_v3
    - module load PrgEnv/gcc13-openmpi-python
    - export CCACHE_DIR="/var/tmp/gitlab-runner/ccache_PITTS/"
    - ccache -z
    - module unload -f itensor
    - mkdir build_debug && cd build_debug
    - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=g++
    - cmake --build . -- -j 15
    - cmake --build . --target check -j 15
    - ccache -s
  artifacts:
    reports:
      junit: build_debug/test/pitts_tests*.xml

build_clang:
  stage: build
  variables:
    SCHEDULER_PARAMETERS: "-p cpu -N 1 -n 3 -c 5 -t 00:10:00"
  needs: []
  script:
    - export MODULEPATH=/scratch/spack-23.2/share/spack/modules/linux-ubuntu20.04-x86_64_v3
    - module load PrgEnv/llvm16-mpich
    - module load py-pybind11
    - module load py-numpy
    - export CCACHE_DIR="/var/tmp/gitlab-runner/ccache_PITTS_clang/"
    - ccache -z
    - module unload -f itensor
    # for -stdlib=libc++
    - export LD_LIBRARY_PATH=/scratch/spack-23.2/opt/spack/linux-ubuntu20.04-x86_64_v3/gcc-9.4.0/llvm-16.0.6-mx55kfz3l4hdavaqhqhfxpblumzpx3nk/lib/x86_64-unknown-linux-gnu:$LD_LIBRARY_PATH
    - mkdir build_clang && cd build_clang
    - export CXX="clang++ -stdlib=libc++"
    - cmake -G Ninja .. -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DPITTS_DEVELOP_BUILD=On
    - cmake --build . -- -j 15
    - cmake --build . --target check -j 15
    - ccache -s
  artifacts:
    reports:
      junit: build_clang/test/pitts_tests*.xml

pages:
  stage: deploy
  dependencies:
    - build_debug_with_coverage
  script:
    - mkdir -p public/coverage
    - mv build_coverage/test/coverage.*.html public/coverage/
    - mv build_coverage/test/coverage.html public/coverage/index.html
  artifacts:
    paths:
      - public/
    expire_in: 30 days
  only:
    - master
